// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebAppPizza.Data;

namespace WebAppPizza.Migrations
{
    [DbContext(typeof(PizzaDbContext))]
    partial class PizzaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppPizza.Models.Command", b =>
                {
                    b.Property<int>("IDCommand")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CommandDate");

                    b.Property<decimal>("Total");

                    b.HasKey("IDCommand");

                    b.ToTable("Command");
                });

            modelBuilder.Entity("WebAppPizza.Models.DetailCommand", b =>
                {
                    b.Property<int>("IDDetailCommand")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IDCommand");

                    b.Property<int>("IDPizza");

                    b.HasKey("IDDetailCommand");

                    b.HasIndex("IDCommand");

                    b.HasIndex("IDPizza");

                    b.ToTable("DetailCommand");
                });

            modelBuilder.Entity("WebAppPizza.Models.Pizza", b =>
                {
                    b.Property<int>("IDPizza")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CommandDate");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Image");

                    b.Property<decimal>("PriceHT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("IDPizza");

                    b.ToTable("Pizza");
                });

            modelBuilder.Entity("WebAppPizza.Models.DetailCommand", b =>
                {
                    b.HasOne("WebAppPizza.Models.Command", "Command")
                        .WithMany("DetailCommands")
                        .HasForeignKey("IDCommand")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebAppPizza.Models.Pizza", "Pizza")
                        .WithMany("DetailCommands")
                        .HasForeignKey("IDPizza")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
